const { Router } = require('express');

const authRoutes = require('./auth');
const userRoutes = require('./users');
const productRoutes = require('./products');
const inventoryRoutes = require('./inventory');
const warehouseRoutes = require('./warehouses');
const orderRoutes = require('./orders');
const cartRoutes = require('./cart');
const partnerRoutes = require('./partners');
const stockTransferRoutes = require('./stockTransfers');
const purchaseOrderRoutes = require('./purchaseOrders');
const notificationRoutes = require('./notifications');
const trackingRoutes = require('./tracking');
const reportRoutes = require('./reports');
const dashboardRoutes = require('./dashboard');
const bankAccountRoutes = require('./bankAccounts');
const courierRoutes = require('./couriers');
const deliveryTokenRoutes = require('./deliveryTokens');
const grnRoutes = require('./grn');
const mobileStockistRoutes = require('./mobileStockists');
const stockMovementRoutes = require('./stockMovements');
const stockAdjustmentRoutes = require('./stockAdjustments');
const cycleCountRoutes = require('./cycleCounts');
const settlementRoutes = require('./settlements');
const exportRoutes = require('./exports');
const allianceRoutes = require('./alliance');
const mobileInventoryRoutes = require('./mobileInventory');

const router = Router();

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/products', productRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/warehouses', warehouseRoutes);
router.use('/orders', orderRoutes);
router.use('/cart', cartRoutes);
router.use('/partners', partnerRoutes);
router.use('/stock-transfers', stockTransferRoutes);
router.use('/purchase-orders', purchaseOrderRoutes);
router.use('/notifications', notificationRoutes);
router.use('/tracking', trackingRoutes);
router.use('/reports', reportRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/bank-accounts', bankAccountRoutes);
router.use('/couriers', courierRoutes);
router.use('/delivery-tokens', deliveryTokenRoutes);
router.use('/grn', grnRoutes);
router.use('/mobile-stockists', mobileStockistRoutes);
router.use('/stock-movements', stockMovementRoutes);
router.use('/stock-adjustments', stockAdjustmentRoutes);
router.use('/cycle-counts', cycleCountRoutes);
router.use('/settlements', settlementRoutes);
router.use('/exports', exportRoutes);
router.use('/alliance', allianceRoutes);
router.use('/mobile-inventory', mobileInventoryRoutes);

module.exports = router;
