const NOGATU_MLM_LANDING_CATALOG = [
  {
    code: 100,
    sku: 'NOG-100',
    name: 'Nogatu Barley Juice',
    category: 'Barley',
    unit: 'box',
    retailPrice: 850,
    partnerPrice: 850,
    description: 'Pure Energy & Naturally Refreshing',
    imageUrl: '/legacy-img/Barley-Mix.png',
    aliases: ['Nogatu Barley Pure Drink', 'Nogatu Pure Barley Drink Mix', 'Nogatu Juice', 'barlet'],
  },
  {
    code: 101,
    sku: 'NOG-101',
    name: 'Nogatu Glow',
    category: 'Supplements',
    unit: 'box',
    retailPrice: 550,
    partnerPrice: 550,
    description: 'L-Reduced Glutathione',
    imageUrl: '/legacy-img/Glow-Pill.png',
    aliases: [],
  },
  {
    code: 102,
    sku: 'NOG-102',
    name: 'Vitamin C with Collagen & Glutathione',
    category: 'Supplements',
    unit: 'box',
    retailPrice: 500,
    partnerPrice: 500,
    description: 'Radiance and antioxidant support formula',
    imageUrl: '/legacy-img/Vitamin-C-Collagen.png',
    aliases: ['Nogatu Collagen Vitamin C', 'Collagen Vitamin C'],
  },
  {
    code: 103,
    sku: 'NOG-103',
    name: 'Chocolate Drink Mix',
    category: 'Beverages',
    unit: 'box',
    retailPrice: 710,
    partnerPrice: 710,
    description: 'Healthy Chocolate with Herbal & Vegetable Mix',
    imageUrl: '/legacy-img/Chox-Mix.png',
    aliases: ['Nogatu Chocolate Drink', 'Nogatu Chocolate Drink Mix'],
  },
  {
    code: 104,
    sku: 'NOG-104',
    name: 'Nogatu Coffee Mix',
    category: 'Coffee',
    unit: 'box',
    retailPrice: 495,
    partnerPrice: 495,
    description: 'Herbal Coffee Mix for Immunity & Energy',
    imageUrl: '/legacy-img/Coffee-Mix.png',
    aliases: ['Nogatu Coffee'],
  },
  {
    code: 105,
    sku: 'NOG-105',
    name: 'Mangosteen Coffee Mix',
    category: 'Coffee',
    unit: 'box',
    retailPrice: 375,
    partnerPrice: 375,
    description: 'Coffee Drink Mix',
    imageUrl: '/legacy-img/Mangoosteen_1.png',
    aliases: ['Nogatu Mangosteen Coffee'],
  },
  {
    code: 106,
    sku: 'NOG-106',
    name: 'Vitamin C with Zinc & Mangosteen',
    category: 'Supplements',
    unit: 'box',
    retailPrice: 580,
    partnerPrice: 580,
    description: 'Vitamin support blend with mangosteen extract',
    imageUrl: '/legacy-img/Vitamin-C.png',
    aliases: ['Vitamin C'],
  },
  {
    code: 107,
    sku: 'NOG-107',
    name: 'Nogatu Black Coffee',
    category: 'Coffee',
    unit: 'box',
    retailPrice: 250,
    partnerPrice: 250,
    description: 'Premium black coffee drink mix',
    imageUrl: '/legacy-img/blck-coffee.png',
    aliases: ['Nogatu Coffee Mix (Dark)', 'Black Coffee'],
  },
  {
    code: 108,
    sku: 'NOG-108',
    name: 'Nogatu Max Fuel Coffee Drink Mix',
    category: 'Coffee',
    unit: 'box',
    retailPrice: 2500,
    partnerPrice: 2500,
    description: 'Max fuel coffee blend',
    imageUrl: '/legacy-img/Max-Fuel.png',
    aliases: ['Nogatu Max Fuel Coffee', 'Max Fuel Coffee Drink Mix'],
  },
  {
    code: 109,
    sku: 'NOG-109',
    name: 'Berry NAD+',
    category: 'Supplements',
    unit: 'box',
    retailPrice: 7998,
    partnerPrice: 7998,
    description: 'Berry NAD+ wellness supplement',
    imageUrl: '/legacy-img/Berry-Nad.png',
    aliases: [],
  },
];

module.exports = { NOGATU_MLM_LANDING_CATALOG };
