const { ROLES, canonicalRole } = require('./roles');

const PERMISSIONS = Object.freeze({
  DASHBOARD_VIEW: 'dashboard:view',
  REPORTS_VIEW: 'reports:view',

  CART_USE: 'cart:use',

  USERS_VIEW: 'users:view',
  USERS_MANAGE: 'users:manage',

  PARTNERS_MANAGE: 'partners:manage',

  ORDERS_VIEW: 'orders:view',
  ORDERS_CREATE: 'orders:create',
  ORDERS_APPROVE: 'orders:approve',
  ORDERS_REJECT: 'orders:reject',
  ORDERS_CANCEL: 'orders:cancel',
  ORDERS_UPLOAD_PAYMENT_PROOF: 'orders:upload_payment_proof',
  ORDERS_VERIFY_PAYMENT: 'orders:verify_payment',

  INVENTORY_VIEW: 'inventory:view',
  INVENTORY_MANAGE: 'inventory:manage',

  GRN_VIEW: 'grn:view',
  GRN_CREATE: 'grn:create',
  GRN_COMPLETE: 'grn:complete',

  DELIVERY_TOKENS_CREATE: 'delivery_tokens:create',
  DELIVERY_STATUS_UPDATE: 'delivery:update_status',
  TRACKING_VIEW: 'tracking:view',

  STOCK_TRANSFERS_VIEW: 'stock_transfers:view',
  STOCK_TRANSFERS_CREATE: 'stock_transfers:create',
  STOCK_TRANSFERS_COMPLETE: 'stock_transfers:complete',

  PURCHASE_ORDERS_VIEW: 'purchase_orders:view',
  PURCHASE_ORDERS_CREATE: 'purchase_orders:create',
  PURCHASE_ORDERS_APPROVE: 'purchase_orders:approve',

  STOCK_ADJUSTMENTS_VIEW: 'stock_adjustments:view',
  STOCK_ADJUSTMENTS_CREATE: 'stock_adjustments:create',
  STOCK_ADJUSTMENTS_APPROVE: 'stock_adjustments:approve',

  CYCLE_COUNTS_VIEW: 'cycle_counts:view',
  CYCLE_COUNTS_CREATE: 'cycle_counts:create',
  CYCLE_COUNTS_APPROVE: 'cycle_counts:approve',

  SETTLEMENTS_VIEW: 'settlements:view',
  SETTLEMENTS_MANAGE: 'settlements:manage',

  EXPORTS_GENERATE: 'exports:generate',

  MOBILE_STOCKISTS_VIEW: 'mobile_stockists:view',
  MOBILE_STOCKISTS_MANAGE: 'mobile_stockists:manage',

  BANK_ACCOUNTS_MANAGE: 'bank_accounts:manage',
  COURIERS_MANAGE: 'couriers:manage',
  APPLICATIONS_MANAGE: 'applications:manage',
  PRODUCTS_MANAGE: 'products:manage',
  WAREHOUSES_MANAGE: 'warehouses:manage',
});

const ROLE_PERMISSIONS = Object.freeze({
  [ROLES.SUPER_ADMIN]: Object.freeze(Object.values(PERMISSIONS)),

  [ROLES.PROVINCIAL_STOCKIST]: Object.freeze([
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.CART_USE,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USERS_MANAGE,
    PERMISSIONS.ORDERS_VIEW,
    PERMISSIONS.ORDERS_CREATE,
    PERMISSIONS.ORDERS_APPROVE,
    PERMISSIONS.ORDERS_REJECT,
    PERMISSIONS.ORDERS_CANCEL,
    PERMISSIONS.ORDERS_UPLOAD_PAYMENT_PROOF,
    PERMISSIONS.ORDERS_VERIFY_PAYMENT,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.GRN_VIEW,
    PERMISSIONS.GRN_CREATE,
    PERMISSIONS.GRN_COMPLETE,
    PERMISSIONS.DELIVERY_TOKENS_CREATE,
    PERMISSIONS.DELIVERY_STATUS_UPDATE,
    PERMISSIONS.TRACKING_VIEW,
    PERMISSIONS.STOCK_TRANSFERS_VIEW,
    PERMISSIONS.STOCK_TRANSFERS_CREATE,
    PERMISSIONS.PURCHASE_ORDERS_VIEW,
    PERMISSIONS.PURCHASE_ORDERS_CREATE,
    PERMISSIONS.STOCK_ADJUSTMENTS_VIEW,
    PERMISSIONS.STOCK_ADJUSTMENTS_CREATE,
    PERMISSIONS.CYCLE_COUNTS_VIEW,
    PERMISSIONS.CYCLE_COUNTS_CREATE,
    PERMISSIONS.SETTLEMENTS_VIEW,
    PERMISSIONS.EXPORTS_GENERATE,
    PERMISSIONS.MOBILE_STOCKISTS_VIEW,
    PERMISSIONS.MOBILE_STOCKISTS_MANAGE,
  ]),

  [ROLES.CITY_STOCKIST]: Object.freeze([
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.CART_USE,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USERS_MANAGE,
    PERMISSIONS.ORDERS_VIEW,
    PERMISSIONS.ORDERS_CREATE,
    PERMISSIONS.ORDERS_APPROVE,
    PERMISSIONS.ORDERS_REJECT,
    PERMISSIONS.ORDERS_CANCEL,
    PERMISSIONS.ORDERS_UPLOAD_PAYMENT_PROOF,
    PERMISSIONS.ORDERS_VERIFY_PAYMENT,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.GRN_VIEW,
    PERMISSIONS.GRN_CREATE,
    PERMISSIONS.GRN_COMPLETE,
    PERMISSIONS.DELIVERY_TOKENS_CREATE,
    PERMISSIONS.DELIVERY_STATUS_UPDATE,
    PERMISSIONS.TRACKING_VIEW,
    PERMISSIONS.STOCK_TRANSFERS_VIEW,
    PERMISSIONS.STOCK_TRANSFERS_CREATE,
    PERMISSIONS.PURCHASE_ORDERS_VIEW,
    PERMISSIONS.PURCHASE_ORDERS_CREATE,
    PERMISSIONS.STOCK_ADJUSTMENTS_VIEW,
    PERMISSIONS.STOCK_ADJUSTMENTS_CREATE,
    PERMISSIONS.CYCLE_COUNTS_VIEW,
    PERMISSIONS.CYCLE_COUNTS_CREATE,
    PERMISSIONS.SETTLEMENTS_VIEW,
    PERMISSIONS.EXPORTS_GENERATE,
    PERMISSIONS.MOBILE_STOCKISTS_VIEW,
    PERMISSIONS.MOBILE_STOCKISTS_MANAGE,
  ]),

  [ROLES.STAFF]: Object.freeze([
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.ORDERS_VIEW,
    PERMISSIONS.ORDERS_UPLOAD_PAYMENT_PROOF,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.GRN_VIEW,
    PERMISSIONS.GRN_CREATE,
    PERMISSIONS.GRN_COMPLETE,
    PERMISSIONS.DELIVERY_TOKENS_CREATE,
    PERMISSIONS.DELIVERY_STATUS_UPDATE,
    PERMISSIONS.TRACKING_VIEW,
    PERMISSIONS.STOCK_TRANSFERS_VIEW,
    PERMISSIONS.PURCHASE_ORDERS_VIEW,
    PERMISSIONS.STOCK_ADJUSTMENTS_VIEW,
    PERMISSIONS.STOCK_ADJUSTMENTS_CREATE,
    PERMISSIONS.CYCLE_COUNTS_VIEW,
    PERMISSIONS.CYCLE_COUNTS_CREATE,
  ]),

  [ROLES.MOBILE_STOCKIST]: Object.freeze([
    PERMISSIONS.CART_USE,
    PERMISSIONS.ORDERS_VIEW,
    PERMISSIONS.ORDERS_CREATE,
    PERMISSIONS.ORDERS_CANCEL,
    PERMISSIONS.ORDERS_UPLOAD_PAYMENT_PROOF,
    PERMISSIONS.TRACKING_VIEW,
  ]),
});

function hasPermission(roleSlug, permission) {
  const role = canonicalRole(roleSlug);
  return Boolean(ROLE_PERMISSIONS[role]?.includes(permission));
}

module.exports = {
  PERMISSIONS,
  ROLE_PERMISSIONS,
  hasPermission,
};
