const crypto = require('crypto');
const pool = require('../config/db');
const asyncHandler = require('../utils/asyncHandler');
const ApiError = require('../utils/ApiError');
const generateOrderNum = require('../utils/generateOrderNum');
const { ROLES, canonicalRole } = require('../rbac/roles');

function isSuperAdmin(user) {
  return canonicalRole(user?.role_slug) === ROLES.SUPER_ADMIN;
}

function scopedPartnerClause(user, warehouseAlias = 'w', inventoryAlias = 'i') {
  if (isSuperAdmin(user)) {
    return { clause: '', params: [] };
  }

  if (!user?.partner_id) {
    return { clause: ' AND 1 = 0', params: [] };
  }

  return {
    clause: ` AND COALESCE(${inventoryAlias}.partner_id, ${warehouseAlias}.partner_id) = ?`,
    params: [user.partner_id],
  };
}

function toCsv(rows, headers) {
  const escapeCell = (value) => {
    const stringValue = value === null || value === undefined ? '' : String(value);
    const safeValue = /^[=\-+@]/.test(stringValue) ? `'${stringValue}` : stringValue;
    return `"${safeValue.replace(/"/g, '""')}"`;
  };

  return [headers.map((header) => escapeCell(header)).join(',')]
    .concat(rows.map((row) => row.map((cell) => escapeCell(cell)).join(',')))
    .join('\n');
}

async function recordExportJob(conn, req, { exportType, filters, rowCount, content }) {
  const exportNumber = await generateOrderNum('EXP', 'export_jobs', 'export_number');
  const contentSha = crypto.createHash('sha256').update(content).digest('hex');

  await conn.execute(
    `INSERT INTO export_jobs (export_number, export_type, format, filters_json, row_count, content_sha256, signed_by, notes)
     VALUES (?, ?, 'csv', ?, ?, ?, ?, ?)`,
    [exportNumber, exportType, JSON.stringify(filters || {}), rowCount, contentSha, req.user.id, 'Governed export generated by API']
  );

  return { exportNumber, contentSha };
}

const getExportJobs = asyncHandler(async (req, res) => {
  const params = [];
  let where = '';

  if (!isSuperAdmin(req.user)) {
    where = 'WHERE ej.signed_by = ?';
    params.push(req.user.id);
  }

  const [rows] = await pool.execute(
    `SELECT ej.id, ej.export_number, ej.export_type, ej.format, ej.row_count,
            ej.content_sha256, ej.signed_at, ej.status, u.name AS signed_by_name
     FROM export_jobs ej
     JOIN users u ON u.id = ej.signed_by
     ${where}
     ORDER BY ej.signed_at DESC
     LIMIT 100`,
    params
  );
  res.json({ success: true, data: rows });
});

const exportStockMovements = asyncHandler(async (req, res) => {
  const { search, product_id, warehouse_id, movement_type, date_from, date_to } = req.query;
  const scope = scopedPartnerClause(req.user);
  const params = [...scope.params];
  let where = `WHERE 1=1${scope.clause}`;

  if (search) {
    where += ' AND (p.name LIKE ? OR p.sku LIKE ? OR w.name LIKE ?)';
    params.push(`%${search}%`, `%${search}%`, `%${search}%`);
  }
  if (product_id) {
    where += ' AND sm.product_id = ?';
    params.push(product_id);
  }
  if (warehouse_id) {
    where += ' AND sm.warehouse_id = ?';
    params.push(warehouse_id);
  }
  if (movement_type) {
    where += ' AND sm.movement_type = ?';
    params.push(movement_type);
  }
  if (date_from) {
    where += ' AND DATE(sm.created_at) >= ?';
    params.push(date_from);
  }
  if (date_to) {
    where += ' AND DATE(sm.created_at) <= ?';
    params.push(date_to);
  }

  const [rows] = await pool.execute(
    `SELECT sm.created_at, p.name AS product_name, p.sku, w.name AS warehouse_name,
            sm.movement_type, COALESCE(sm.quantity_change, sm.quantity) AS quantity,
            sm.before_stock, sm.after_stock, sm.reference_type, sm.reference_id, sm.notes
     FROM stock_movements sm
     JOIN products p ON p.id = sm.product_id
     JOIN warehouses w ON w.id = sm.warehouse_id
     LEFT JOIN inventories i ON i.id = sm.inventory_id
     ${where}
     ORDER BY sm.created_at DESC`,
    params
  );

  const csv = toCsv(
    rows.map((row) => [
      row.created_at,
      row.product_name,
      row.sku,
      row.warehouse_name,
      row.movement_type,
      row.quantity,
      row.before_stock,
      row.after_stock,
      row.reference_type,
      row.reference_id,
      row.notes,
    ]),
    ['Date', 'Product', 'SKU', 'Warehouse', 'Type', 'Quantity', 'Before', 'After', 'Reference Type', 'Reference ID', 'Notes']
  );

  const conn = await pool.getConnection();
  try {
    await conn.beginTransaction();
    const exportMeta = await recordExportJob(conn, req, {
      exportType: 'stock_movements',
      filters: req.query,
      rowCount: rows.length,
      content: csv,
    });
    await conn.commit();
    res.json({
      success: true,
      data: {
        filename: `stock-movements-${new Date().toISOString().slice(0, 10)}.csv`,
        content: csv,
        row_count: rows.length,
        export_number: exportMeta.exportNumber,
        sha256: exportMeta.contentSha,
      },
    });
  } catch (err) {
    await conn.rollback();
    throw err;
  } finally {
    conn.release();
  }
});

const exportSettlements = asyncHandler(async (req, res) => {
  const params = [];
  let where = 'WHERE s.is_deleted = 0';

  if (!isSuperAdmin(req.user)) {
    where += ' AND s.partner_id = ?';
    params.push(req.user.partner_id);
  }

  const [rows] = await pool.execute(
    `SELECT s.settlement_number, o.order_number, p.business_name AS partner_name,
            s.amount, s.method, s.status, s.expected_at, s.reconciled_at,
            s.reference_number, s.variance_amount, s.notes
     FROM settlements s
     JOIN orders o ON o.id = s.order_id
     JOIN partners p ON p.id = s.partner_id
     ${where}
     ORDER BY s.created_at DESC`,
    params
  );

  const csv = toCsv(
    rows.map((row) => [
      row.settlement_number,
      row.order_number,
      row.partner_name,
      row.amount,
      row.method,
      row.status,
      row.expected_at,
      row.reconciled_at,
      row.reference_number,
      row.variance_amount,
      row.notes,
    ]),
    ['Settlement No', 'Order', 'Stockist', 'Amount', 'Method', 'Status', 'Expected At', 'Reconciled At', 'Reference', 'Variance', 'Notes']
  );

  const conn = await pool.getConnection();
  try {
    await conn.beginTransaction();
    const exportMeta = await recordExportJob(conn, req, {
      exportType: 'settlements',
      filters: req.query,
      rowCount: rows.length,
      content: csv,
    });
    await conn.commit();
    res.json({
      success: true,
      data: {
        filename: `settlements-${new Date().toISOString().slice(0, 10)}.csv`,
        content: csv,
        row_count: rows.length,
        export_number: exportMeta.exportNumber,
        sha256: exportMeta.contentSha,
      },
    });
  } catch (err) {
    await conn.rollback();
    throw err;
  } finally {
    conn.release();
  }
});

module.exports = {
  getExportJobs,
  exportStockMovements,
  exportSettlements,
};
